apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: your-namespace
  name: telegraf-postgresql
spec:
  selector:
    matchLabels:
      app: telegraf-postgresql
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf-postgresql
    spec:
      containers:
        - image: telegraf:1.23.4
          name: telegraf-postgresql
          volumeMounts:
            - name: telegraf-postgresql-config-volume
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
      volumes:
        - name: telegraf-postgresql-config-volume
          configMap:
            name: telegraf-postgresql-config